# selection_utils.py
import os
import numpy as np
import pandas as pd

LABELS = [
    "Not Interesting",
    "Slightly Interesting",
    "Moderately Interesting",
    "Very Interesting",
    "Extremely Interesting",
]

SEED = 42
N_PER_LABEL = 5
SELECTED_25_PKL = "data/selected_uniform_25.pkl"

os.makedirs("data", exist_ok=True)

def canonicalize_label(val):
    """Map raw values to one of the five canonical LABELS."""
    if pd.isna(val):
        return None
    try:
        as_int = int(val)
        if 0 <= as_int <= 4:
            return LABELS[as_int]
    except Exception:
        pass

    s = str(val).strip().lower()
    mapping = {
        "not interesting": LABELS[0],
        "slightly interesting": LABELS[1],
        "moderately interesting": LABELS[2],
        "very interesting": LABELS[3],
        "extremely interesting": LABELS[4],
    }
    for k, v in mapping.items():
        if k in s:
            return v
    for v in LABELS:
        if v.lower() == s:
            return v
    return None

def build_uniform_selection(df_images, save_path=SELECTED_25_PKL, seed=SEED, n_per_label=N_PER_LABEL):
    """Sample n_per_label per label (oversample if needed) and persist the selection."""
    if os.path.exists(save_path):
        return pd.read_pickle(save_path)

    df = df_images.copy()
    df["interestingness_label"] = df["interestingness"].apply(canonicalize_label)
    df = df[df["interestingness_label"].isin(LABELS)].copy()

    rng = np.random.default_rng(seed)
    parts = []
    for lab in LABELS:
        pool = df[df["interestingness_label"] == lab]
        if len(pool) == 0:
            raise ValueError(f"No images for label: {lab}")
        replace = len(pool) < n_per_label
        if replace:
            print(f"[warn] Label '{lab}' has only {len(pool)} items; oversampling.")
        sample_idx = rng.choice(pool.index, size=n_per_label, replace=replace)
        parts.append(pool.loc[sample_idx, ["filename", "interestingness_label"]])

    df_sel = pd.concat(parts, ignore_index=True)
    df_sel.to_pickle(save_path)
    return df_sel

if __name__ == "__main__":
    # Load directly from the CSV generated by rate.py
    df_csv = pd.read_csv("data/interestingness_results.csv")  # ← correct file
    df_sel = build_uniform_selection(df_csv)

    print("Saved:", SELECTED_25_PKL)
    print(df_sel.groupby("interestingness_label").size())
